### Variables, deberia de ser HOST pero lo reuso porque es el mismo srry
@port={{$dotenv PORT}}
@host={{$dotenv DB_HOST}}


### POST de la funcion crear un usuario correcto
POST http://localhost:{{port}}/api/user/newAccount
Content-Type: application/json

{
    "username": "Carlosdbs",
    "password": "Mariadbesito"

}

### POST crear usuario = contraseña corta
POST http://localhost:{{port}}/api/user/newAccount
Content-Type: application/json

{
    "username": "Maria32",
    "password": "Mari"

}

### POST crear usuario = contraseña sin mayuscula
POST http://localhost:{{port}}/api/user/newAccount
Content-Type: application/json

{
    "username": "Maria32",
    "password": "lariadbesito"

}